# Generated by Django 4.0.1 on 2022-01-14 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='attachments',
        ),
    ]
