# Generated by Django 4.0.1 on 2022-01-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_question_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='attachments',
            field=models.FileField(null=True, upload_to='question_attachments/'),
        ),
    ]
