# Generated by Django 4.0.1 on 2022-01-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_extuser_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extuser',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
